name: Test python-version inputs

on: [workflow_dispatch]

jobs:
   test-prerelease:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.14.0-alpha.4'  # NOTE: no other pre-releases available in Quansight-Labs/python-versions
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: ${{ matrix.python-version }}
          freethreaded: true
      - name: Install dependencies
        run: |
          python -VVV
          python -m pip install --upgrade pip
          pip install -r requirements.txt

   test-suffix:
      runs-on: ubuntu-latest
      strategy:
         fail-fast: false
         matrix:
           python-version:
              - '3.13t'
              - '3.13.0t'
              - '3.14.0a4t'
      steps:
         - uses: actions/checkout@v4
         - name: Set up Python ${{ matrix.python-version }}
           uses: colesbury/setup-python@ft-wip
           with:
             python-version: ${{ matrix.python-version }}
         - name: Install dependencies
           run: |
             python -VVV
             python -m pip install --upgrade pip
             pip install -r requirements.txt
    
   test-ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: '>=3.9 <3.14'
          freethreaded: true
      - name: Install dependencies
        run: |
          python -VVV
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
    

   test-hyphen-ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: '3.13.0-alpha - 3.13.0'
          freethreaded: true
      - name: Install dependencies
        run: |
          python -VVV
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

   test-x-ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: '3.x'
          freethreaded: true
      - name: Install dependencies
        run: |
          python -VVV
          python -m pip install --upgrade pip
          pip install -r requirements.txt   
   
   test-pythonversionfile-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: colesbury/setup-python@ft-wip
        with:
          python-version-file: 'pyproject.toml'
          freethreaded: true
      - name: Install dependencies
        run: |
          python -VVV
          python -m pip install --upgrade pip
          pip install -r requirements.txt   
