name: Test python-version inputs

on: [workflow_dispatch]

jobs:
   test-prerelease:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.14.0-alpha.4'
          - '3.13.0-beta.3'
          - '3.13.0-rc.2'   
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: ${{ matrix.python-version }}
          freethreaded: true
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
   test-ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: '>=3.9 <3.14'
          freethreaded: true
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
    

   test-hyphen-ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: '3.13.0-alpha - 3.13.0'
          freethreaded: true
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

   test-x-ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: colesbury/setup-python@ft-wip
        with:
          python-version: '3.x'
          freethreaded: true
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt   
   
   test-pythonversionfile-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: colesbury/setup-python@ft-wip
        with:
          python-version-file: 'pyproject.toml'
          freethreaded: true
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements.txt   
